### ISSUE TITLE
Calling cv::applyColorMap() in FrameQImageConverter breaks compatibility with ubuntu 12.04

### ISSUE THREAD

**Issue by arneboe** [rock-core/gui-rock_widget_collection#3]
Ubuntu 12.04 only contains opencv-2.3. However the FrameQImageConverter calls cv::applyColorMap() which was introduced in opencv-2.4. This breaks compatibility with ubuntu 12.04.

Full compile error:
```
 In file included from /home/aboeckmann/git/rock-artemis/gui/rock_widget_collection /src/image_view_old/ImageViewOld.h:25:0,
                     from /home/aboeckmann/git/rock-artemis/gui/rock_widget_collection/src/image_view_old/ImageViewOldGL.cc:9:
    /home/aboeckmann/git/rock-artemis/install/include/frame_helper/FrameQImageConverter.h: In member function ‘int frame_helper::FrameQImageConverter::copyFrameToQImageRGB888(QImage&, base::samples::frame::frame_mode_t, int, unsigned int, unsigned int, const char*, size_t)’:
    /home/aboeckmann/git/rock-artemis/install/include/frame_helper/FrameQImageConverter.h:192:29: error: ‘applyColorMap’ is not a member of ‘cv’
    /home/aboeckmann/git/rock-artemis/install/include/frame_helper/FrameQImageConverter.h:192:63: error: ‘COLORMAP_RAINBOW’ is not a member of ‘cv’ 
```

**Comment by goldhoorn** [comment]
In general:
Rock does not support 12.04 any more.
If you really want feel free to provide a backward-compatibilty fix.

Otherwise i assume this will become a "wont fix"

Best,
Matthias


On 10.02.2015 10:48, Arne wrote:
>
> Ubuntu 12.04 only contains opencv-2.3. However the 
> FrameQImageConverter calls cv::applyColorMap() which was introduced in 
> opencv-2.4. This breaks compatibility with ubuntu 12.04.
>
> Full compile error:
>
> |  In file included from /home/aboeckmann/git/rock-artemis/gui/rock_widget_collection /src/image_view_old/ImageViewOld.h:25:0,
>                       from /home/aboeckmann/git/rock-artemis/gui/rock_widget_collection/src/image_view_old/ImageViewOldGL.cc:9:
>      /home/aboeckmann/git/rock-artemis/install/include/frame_helper/FrameQImageConverter.h: In member function ‘int frame_helper::FrameQImageConverter::copyFrameToQImageRGB888(QImage&, base::samples::frame::frame_mode_t, int, unsigned int, unsigned int, const char*, size_t)’:
>      /home/aboeckmann/git/rock-artemis/install/include/frame_helper/FrameQImageConverter.h:192:29: error: ‘applyColorMap’ is not a member of ‘cv’
>      /home/aboeckmann/git/rock-artemis/install/include/frame_helper/FrameQImageConverter.h:192:63: error: ‘COLORMAP_RAINBOW’ is not a member of ‘cv’
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/gui-rock_widget_collection/issues/3>.
>


-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by arneboe** [comment]
I didnt know that 12.04 was no longer supported. Sorry :)
